# base config
dist: xenial
language: rust
rust:
  - nightly
cache: cargo
services: docker
sudo: required

# environment
matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
  
    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

# scripts
before_install:
  - set -e
  - rustup self update
  - rustup component add rustfmt-preview
script:
  - cargo fmt
  - cargo build --verbose --all
  - cargo test --verbose --all
after_script: set +e

# notifications
notifications:
  email: false
