version: 2

jobs:
  build:
    branches:
      ignore:
        - auto
    docker:
      - image: rustlang/rust:nightly

    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Check code format
          command: |
            rustup component add rustfmt-preview
            rustfmt --version
            cargo fmt
      - run:
          name: Build
          command: |
            rustc --version
            cargo --version
            cargo build
      - run:
          name: Run Test
          command: cargo test
      - save_cache:
          key: cache
          paths:
            - "~/.cargo"
            - "./target"
