version: 2

jobs:
  build:
    branches:
      ignore:
        - auto
    docker:
      - image: rustlang/rust:nightly

    steps:
      - checkout
      - restore_cache:
          key: cargo-{{ checksum "Cargo.lock" }}/1
      - run:
          name: Check code format
          command: |
            cargo install rustfmt-nightly --force
            rustfmt --version
            cargo fmt
      - run:
          name: Build
          command: |
            rustc --version
            cargo --version
            cargo build
      - run:
          name: Run Test
          command: cargo test
      - save_cache:
          key: cargo-{{ checksum "Cargo.lock" }}/1
          paths:
            - "~/.cargo"
            - "./target"
